#ENC[AES256_GCM,data:xyOpZ1FzAdpl9P8KyX5sKJn403NXsk4uihMNOLTDU8dyhzHnBsYLRDzL5K1yIblsPPaviC55k7JpPVI=,iv:a24iLQcdsyTjvZ+aVYmUj22s/OjoyAxWA+rG1uke7mc=,tag:4wbg+gAcfsMwPSk2zulARQ==,type:comment]
#ENC[AES256_GCM,data:jwv0VEzOoXhXECmKsNPXGfYk3/45Tm+4rRz/SQGQ8zTo/LjiPOkGXy7xd5rAQvPZ,iv:DTAaXQmHb9v/tg21JmvKtZN3B5oseEKN4m2ZELBRgCI=,tag:GTgUMptWhWmdwKlEuTWidA==,type:comment]
#
#ENC[AES256_GCM,data:XqupGUbR+nWwedbzntl5u1W8w9JIt0mRU5r/zT6SCODOpVhHKYwuG1cJM2k+wQ==,iv:77l1xB3Wnl55mkdIsdA3rznnCre8073uPVeFHH9X/P0=,tag:MB1SZgdp6IrJd9bFNsWXcw==,type:comment]
#ENC[AES256_GCM,data:HY8OJqMuXQ+K70fFvyRKOxYrGGk4jXyqN13N31omiHfd+73ajTf1,iv:S5R0bY3+FGui/E4QuElgrgQcsAKeq2LmW9WS9P58YBY=,tag:v8VSkcmMtWpaWU9IUJLGwA==,type:comment]
k3s_token: ENC[AES256_GCM,data:wnG7TMFU7jp8EGsy6tlrKAvLo9Hr8Z2QmoOzOeaUqJkyPcn/G1q4i9Fl5HpoAwn+YD5BYD8tc589KYikuLnIcg==,iv:LfoeK5nmp+EGjc0OT4i8O1eOg75qZ09bEKWkf7WD+Ek=,tag:OboFeKqW+yFjvyrgIDT+/Q==,type:str]
#ENC[AES256_GCM,data:GtGm4Kt22kOtrLEf8saB7peTUR8O/wkB,iv:u467obsjlSEtLf3wJtk5H1i9cTWLqay7L2g1TUGC4NU=,tag:onJDYqzXhRrv4pF8gQHcCQ==,type:comment]
tailscale_auth_key: ENC[AES256_GCM,data:Bv3iukMZsvkTltZ2PWcc1U9hTJ2sM8wcuHmnPWUAE4KQ1WscL1FdlBWjr2A5E+7pnx+TfbJgJSsAArKI0g==,iv:5TOFfh6afHGt01GJB9MBwx4VfqZzbJG2ilMkBtg0IdI=,tag:veILOsKlHFA5Ubba1QBf/w==,type:str]
sops:
    age:
        - recipient: age19pulnwtzah3x4xfp8rsajr7vzddct6lljeurfgu3pc7t9v3cy4gq6xe297
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQk5CZFczeWxVZmdYc1Fk
            SEhmUklUbEQxU2JaR0h0QTFGbkt6aDJaaENFCkU0WUJqOFpyQ0R5NFBJWHIrbFdu
            YVZrOXh3c0VBYnZBa2pCZnpKTmVTQzgKLS0tIFlqaWpFTyt2TGZZQTlXT1BNODlh
            R0RicXl5aUU4Y2k0dS9jenp0dTduNUEKgqMWLvW8oebbgVAY78mZefOHQnvjyFO2
            4OeiPClrzJ/ANOGTxxSMbIwAkl0H4XHrzHnrZZU3w1fhfzQSf6pJaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T00:34:42Z"
    mac: ENC[AES256_GCM,data:sBLgdfRojVHORK5OB5bCdLd/3Kt/6JU1+H9fON1WFOi5V5P8+j3zwxl/1pz9CSlFiS9aCEnLBGA/Egh+3dFXFXbmo8SpB5BKk6f84YurNPfu+jqmjE8+VK9qEPRyXZ6tquINSzJRjM534i+gJ6gBpaBCCLT4S1g0OKL9yGNg93s=,iv:CGS+2Dv09LxvXgivgxKNQmfmEADVxlskettrQqk5ods=,tag:r2BUPgYBZJHiWn7UfIyM1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
