#ENC[AES256_GCM,data:8OjOWEII2vgQxpW9BTXzPa5N/osGBgwVSo9CRezYjzvxko79RzzUk8CvpT4OeoSGsHS8qAtsOrVOt0s=,iv:pIN40mGQ8lNopNIGbweTrZN8JIEK3VBDWL45EB+QR8o=,tag:OLrRJeFtqy+Pcv7YvndJkg==,type:comment]
#ENC[AES256_GCM,data:C7xRijR7JCuFe99ntRCqwJ5IdOI6gGYzrLO48eUC0o1cNpYhgQVWMZHPTOJVyaUC,iv:5OnmiIQOVbDCshA6+s2gj0jJAgtds0hKdyt49xon0iU=,tag:aWDxzbCNbAJZyax7piqIMg==,type:comment]
#
#ENC[AES256_GCM,data:XkqC8xzzZxLOMAWeYs91mErxCNvWBS1o9XlI98GGnV4VEqJTk0ysRIWNqsOcow==,iv:PxfhsvBkSs+klOZqT8cBIDrY4ubY3OPqPHNaPj15LyY=,tag:q1CMJ+DTRHd40myRdizvJQ==,type:comment]
#ENC[AES256_GCM,data:lw10tNbudd8XKCEZK82kBW7aw7a3sAFzIi0HG34Ia4xpt5xNmpsd,iv:2L/jqEMPzzObY9ukb5f/CyZQCJ/90NP+KngTrnFxPio=,tag:TA0tGHFgkOzbI0VPVpJV0A==,type:comment]
k3s_token: ENC[AES256_GCM,data:7a/ZyKQdbXN5Hab0VQqzc0W5pY+4dHMMGuO+JaXtXynYkDXkP0ntEr+36bw8N4qWfva3RKHSoUrhvdqafyp+nQ==,iv:a/wfdayFqGxmL8i7VWUpkqbLGC4VlI81thFtLuFUuso=,tag:jUosCL62XUzOmAakWt6uog==,type:str]
#ENC[AES256_GCM,data:3gHwz12A6/5RqDvSkjCBp0pMyIU+vX/7,iv:QDZ8MrXwx/pYrJUTXs2wy87hG0suIAN+D/k9rtP/b/4=,tag:9ruEbTA9k8CLBXnDbM/nTA==,type:comment]
tailscale_auth_key: ENC[AES256_GCM,data:YmhAANUVZ8kKOX1QFI8Ni3qOfJEr3QhhAZInyK2TYRoY+nn3xnEj9F790I6u5jXHRVhZeGhg+5wymuE8jQ==,iv:PGS8jVQPT6sUxEjP9G7fuWIdP1KZ2oxgqiMIxpXeTsE=,tag:Dri3N9n+tZdwi3oypiy8EQ==,type:str]
sops:
    age:
        - recipient: age19pulnwtzah3x4xfp8rsajr7vzddct6lljeurfgu3pc7t9v3cy4gq6xe297
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS24wWTV2dS9mM0lwUnVU
            RnltRzdDRkJwd1ZnbXB4TmFTalIxUndIaVhNCjdBU2NmVnlDL3pZSmk0aTlxSGJF
            MjJtNmtGMjRiOW9mNVNXMVlpOW5nNWcKLS0tIExHK3IxVmJXWDVia1hCaWh5MU5Z
            ZFUrbUF1Z0J5Q0tldkVFeXVaSzZtdEEK6zQ4slBLTkPl89VLwnhRZ52UhI8adGbq
            JW7sWrNrJMillC81xqwDHzO7Ygtf9y0TXXkMjIOYWrY5qaCGMKsJXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T03:49:37Z"
    mac: ENC[AES256_GCM,data:r5LD8ex4a8QheyicRi0gjtVBSqwSNrImyEwBSue1NeARE70nZAKwMyJg4j1dFi85rsq+5EraNIJmHubiPPuE0HbOWx14kvcJbwOh5B4gYNSbYjALLuVkDXSGKOtiecqWu6GXdMayXQKEPPHAi+C3Kfqw6ByZsbR5l6lU6bXwZus=,iv:otgVg10wEfpci1cbzAP3w2FR+QcUZWEHntTVYVBbVy4=,tag:W7FzuLOa0GrAZp9YHtcePQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
