creation_rules:
  # Encrypt Ansible group vars
  - path_regex: ansible/group_vars/.*\.sops\.yml$
    age: >-
      age19pulnwtzah3x4xfp8rsajr7vzddct6lljeurfgu3pc7t9v3cy4gq6xe297
  # Encrypt K8s secrets
  - path_regex: k8s/.*secret.*\.sops\.yml$
    age: >-
      age19pulnwtzah3x4xfp8rsajr7vzddct6lljeurfgu3pc7t9v3cy4gq6xe297
