apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - pvc.yml
  - mail-secret.sealed.yml
  - network-policies.yml
  - backup-cronjob.yml
  - backup-r2-secret.sealed.yml
