---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-mail
  namespace: blog
spec:
  encryptedData:
    password: AgB5I6MpsHJ9IjP9z+U7mCX4NeLhM1tMdym9lL7S4ZTYf7ryabTx/YMdkdyllsmdhlpUQhZNyaWyIsmO/tRb5TVIfaVsEoyW3xizKUy2nuD1+fmOGgWSqXswg2iuN/vRNos6Ea5TtXvSJK4L9Q1otyh69gHyoCHTpgAsnOuYUDwH76rDQ5XuhLSO1VGYxcqswXo9m8Wldez+J/ZXXvzLCID7vuEkN9H6jnAC+xmupae0ODJzc4G5twvxkCjskvQR1/Eax7TDR8Uh3sNL1LD9T7LUTdYWDsScytQ32AlPVbIzaXZkXvA8Ffg5XjL5vKtOANL1PtinJKNZGx4pCQWHlOE+/7tpWGSbJwxds09VqqVkTGssG9CTcagbqVfxrXyeZ+wkyoACH01Pk/3ZlBQdtgArR+6B851dWEkGqVqQkA6L6ghOQeSd2r6OVSYba6fVudT907QF75lwWjby4TwgO99ZA2XgECdHZ/vKF6CAAP95HAkMcRQ64glAjuaob8wtwH41CF0cHUmsfrf3hGtNwyoWSfOPzROP6S7Uj/9nMn35hQ7oMg97g7ReFWjppFEM1k2zzL4CwEcp088IOEQEnmK0sri/p3rj1iScfgmh4Sig/5KZ2HlXMU7h5MbDEt3sklfvXB5Xoewywd3XCnuj0o/qkqk66m3hBmKnQGKkqkAMI+TofycNWZo6W6maaDUF3UJXwrwxZSb2jtDkd5PKlv+pT2O2KF5A3VmBJJhazred3hLS8oPZ6tdwq+LTgrvBIJ+YbipgUAVpit4nFLYN+NwyhMpsPUeoj3fXvp9Z1sLXOzDozxfdXfBuTzo=
  template:
    metadata:
      name: ghost-mail
      namespace: blog
    type: Opaque
