apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingresses
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: ingresses
  source:
    repoURL: git@github.com:cjwillis48/k8s-infra.git
    targetRevision: main
    path: k8s/ingresses
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
