apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.8.1
      helm:
        releaseName: longhorn
        valuesObject:
          defaultSettings:
            backupTarget: s3://k8s-longhorn-backups@auto/
            backupTargetCredentialSecret: longhorn-backup-creds
          longhornManager:
            env:
              - name: AWS_ENDPOINTS
                value: "https://0a5f0f60df717358942f04cca4d61c3a.r2.cloudflarestorage.com"
    - repoURL: git@github.com:cjwillis48/k8s-infra.git
      targetRevision: main
      path: k8s/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - SkipHooks=true
