---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-creds
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCEcWPFXEXxXgPvbjEvyGK4VoekibSFWWZvFdyfsRjAlap0+cfsMHCCc5AH/TeBWf98jZxmdv/pb5+Xot3Pvt3qk2LGLDl7JArW2/aR6mwBIcNOJv4bDZmdbRmW7hZi7SV6kah2r0LSuc7nYJu3ONjJJ2K+ZN90BJAffYC1aiYuzOeHEhdB4lReNyLkQSsgumpCPewnU3u+BlLDrI93XiUJ0pNLrL8M700Ka1l/lDF4LFD4PxBpOWGJSOMYbyK+3sgczCP+Ywyt9N730a9A8+tIWYUgyjTpri6I8pXfAyc+9GneliFlEdm0cdgthrjn1W5grq/oikHto6IQWZI5VyRcWVd0coluhdEDZ2kgoB+ClLkKXhknlDyE1XAPLstL14aEK2o3PW9mZpX0YmbwUXPGgqRPMsHwT4mTdWkpzI+1hUWLDc6CPo5nPGzoh+s4tOMlcxiloq7UL3DQyZOhINKo6mBs5QYJPIj7x5s5Nwo7mzA5a4lR6R4kVKF1wN7K0CN84rSLYAX3Orp9B5C7lYzNViSHZHNXfo1Pi1ZiX2gUlK5hhyQOA1O2TDFd4wMHMrcdWo6gOm3XlqdEbkQ7kAtzh7jIsEQRCHoxPn7CMiDAySeV8wh3BceiaK9unngYKcVLkFTn+OlzIU9ZbY1i98rj84dizLVmk4TUCL+O3MxhOM42O5jFYXpqGJtMw/PyzhiM9sZDMPd0p6/esEhncdt4uVaXxJ7rkPU8oR+skLlXYA==
    AWS_SECRET_ACCESS_KEY: AgAscYR7yCpwKpMkc7VVqLUdm90tavNvwRJhwpvZZGRpE8RcC4EpIQThjoSv+4JnFDIZ9A0JruWFdWtr5LOiiTLzvMBB2GAn5F1je5PLNh80wJ0Fxa4KhmyNywlwA19aQ0LFQLJsVijiw/f/AUi0yKRI3xbhxYuPoa2s19B2Yx3y83Sqa7HIWCG1rAd9ys5xJ0Jul72VnayQ6ML+34ioM66eE8NH3tRzt2D+jE0ScQCQVFaOnV2lMdOrnr51JBJutX4SFSXkRrrQ5IVkdpWzWZb+F7XFdQXSMmNtUxaSuEu2PurlmJyxKxOaD+pQCKZDh9ozHMJ7mBlhPYtsImLHyPOIqOkLtWiU6eL0VwYzaCvef5BQql2fwoDOlNCgEgkwD8udgty6+oiZ0pCbueXIWfIIennWAvHwybbL7FT5YUmEEoabNFSSQGLa/rZXelh6cVRQL2rSN/17yJDeID3YGjkH+pWuASgIJwKu0PjdxKsgqyXG5lnWrIIfQWUYtEL0grxNkR97KTkI64GkKG7jwuLaa12lTy85HFRASmks7ECPEq2+WUi0+wWyCcuKzSXni0zzgmwRfEgpZFkyCDCp9uxk3nx9B92yEknba7gYXJsTzlQwdJDME7Bvm0+k8myDP++nvj537AphLvSrx/L06DCKqQuikUwDoULnlMqkQxTrUe8SMeQB1zblkcqwSaRYQX5kVHBuziytD3iEB6Zj8qoBaiANttGuu15RslbcO6jYAoE+b9VH/U7GjKCGbMiZT0mMFrQtAJ1n2TrAlti1FU1X
  template:
    metadata:
      name: longhorn-backup-creds
      namespace: longhorn-system
    type: Opaque
