---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: axiom-credentials
  namespace: logging
spec:
  encryptedData:
    AXIOM_DATASET: AgAUNlUhmtrUUml0XnIEI5R4J6k9etZMr2Y386dPoXNb+uHQo6uaRz2I1pAG5u0pQZaiiBbihCZ+4YBuGJ5hTeqwQKjcJYJv5cs/Mrkw8v6TbO95izzN2SGWWWTnLpnX0h2Vs4IncE8/8sjf/A8IrZkuktt276tsRZmquqiQQWenF4FY5i1d9w83tpom7pySdgvGD6Fr51zh5P1tCBH//ItmRD6i0YBPAhXMGHofJWLsrvht6JdV9qKEbzBRlKsaNxnx/mUtqpG6T8L3RHuJJPuwjFgO/x8VgDMkKvp8wN9UlKJ81JVoNcYx8mS/DowZPLDA7KWLT4t94eNXnUK0vujN16f5rhKCZW+4vrFwvoq1/COj7Me/cKBLWu7IxCpLp6iILfIwFZxRwWDnUKCuNfJ/wvA/8LCJ/ys4kk1tl7VTI4BkyUv1qE0d2tj+h5ytHkVCs/Q9tSHzZYGvB3bvbMwzIuiyscx/QYIkC+6IlfWcjfBDnRnc2RVvM+GcuTQ5TOR4a58IlPxhaAF88KrGYShFyJAqBO3C3aevIngklMvgxVQ8rh0j4LJEMWfr3M0C5JXWZS9t7AN0Ho2ZIRyji9EFSEdr1eKJBRo6I0MN8QS9f0y0UIyy7pjBbyNdTPrP6FBWXBML4wydQvBeCpXXCxxsfyeFXyhFp6jGn+sKoxLey/dX1fxI8aSQdtEyZQEwEg4=
    AXIOM_TOKEN: AgCeyHdVk9vDLVIVZCJ3koFBdnQ8ocon32momhR1TenmjQEmCr0oyOtP0ZLVdOsa2TFEhO5EeRGP7K7GmvNME3QEQhtrDJI93RKwRawVF/oiHcC08Bfw+MDkkFH8Zr+e2b+BSNd71ib0OuWL3hrrU6CR3B6iZ/ZaGnnkmunW9/RsoCytXZhQhc7SIWI3BbXojzkdHzQitd3jxlN8PmXbm/xIWTQY5NJRB9EofWFs4XfCsEr4pY+kclAQPO4PJIgbvK7d6sRq6GeZAoDUp8jTSFZmQpBw5Jqo/JqTNpJP0rzQcARzAwIJH7tACuEcXWRAVPA+iKOwzS6Su2eODLei+BwJFBfykW7boD410K0kQL1jfsINbuAdgQChIcx6kkgsh10MomFkDs2BHKur63zy7mW+nK5ioeChOzvQsjkNR4G19HnvOzaYf+g3IPTc3J3iQAmalQsjy0hxGFrT+DevsEjsEZkJkUfjucL88NKlctjX8YewL4O77n/fSvJ31rQJKtbSD+rmsI3Lf10VkZfQN1hPLiBVE1+OEP6Ibeit5PLtWbZOGB6dYKETarlPboMZCLGg8DU92vtT6zVwF1zqJKvex1ClHcAO+zH8JsJfSwykzI9XYy46JUJtiIFtIwRFUZ5cJx8ybr+oVVspq0CnduuSUL8lOCDTEVsQYhnLjPaqOmX9fD/XB+Sl0fy0frGO06w=
  template:
    metadata:
      name: axiom-credentials
      namespace: logging
