---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: axiom-credentials
  namespace: logging
spec:
  encryptedData:
    AXIOM_DATASET: AgBea8J/7bwBJy2CgJRtBAOyNHdkmFEJ87bZRZNOOOnz97bUcwbAjcdBRkTuUdKMThp2YnCOOR6kRybex9Qu7PNokFNykldpd3/bLl3G3AO8iABXS6oXdNq+9ErjVQzpP+q9zn89Gj3cQjdtxb4hoUPRVD4NGsQlSVUNu0snquQsYZtb8SInT38uLq1SHcNHbcJMkJ2LcItgRw+uFXPetbK+BiofbzWznr02B9uIZD9XqdMje1hPb9A8ceau1mdjt+GT62PgRAj+crf3serwFXVfNAX/ba3DsSB77VGR63KMqJRMI6LtGSHYaICyNPuV4VO/skjQmYONK6wvjiSz+Paing2wYlgEZguLqbFM9QcY6oz6HwA1nC+joR9AXhg23Ppec/aVzTyr9ETc26Yh6cp4VAdr4e4er2a27M3VBTRU1KADqsTPitSyIU8i05tIh+G8ttd4s41HPGRN9PnplkjS91I3fPg00EQf6PcmIrKe2GSkIpNpyBViLDsRwvR6OfrzWq0Synw7hNOZld3LdAKBoTvYXxUlEyoEivIX3Fa7/p7X9TGAQCvH/sc/w4gmQp1xy47mFUlu2Iek2PfNWA61uEEs0P+pet6gXkKbFixFmYY9GABcAcU1bt4x4fWCEEbpHfm9Bx5Al4Wo3blZeldMaDGo9Jar6OXtnMjoO6+xB1xRdMYyqurZtrhJwwlspHMXu2CuBvdaclKjOVi90Ks=
    AXIOM_TOKEN: AgBSMtwE46ZPNaEk3qruhnJxQCGkpwQuvjmBg+kyrHpTr0/3YzmIzHIywQHDxyg6WzF3dReRzIksf6cKPJxPJH8/gWqKeWZ2ZpT65CzhbXyyqNyeLBxOcN7W/rzuqsOylSYMeu0V+IVVzPFUssro8oHsODY2wYb/1g5+YxPkQWmUp3ONPyHpUN8DeLWeLiCOmboBStipmjNSJGSUCdKD0O2sZsB1M0lW2e1oGlXTLYLpHPR3ucxkChiIhNLoXbtWdl3PABgZW85v/9YQ/zpumfO86Wxcvn9sTph02lV1xT8shLbZhso8zgwQNSWiDZ7Uy0fwfRyI1EXY+GlBRC2L1am4R1iPsdj4A0u/XIog/syBHqgMP+4ea4tqV8lDrIGC+YPEtz5pl86b4MM75WkuzlN/pNuvyXrbOwL+jcMyp9ss4oBxzpJ6DkqkO6oJDi2feIgQ+8bFnYespRJHV4eOYKwNwe9u1jfjQ/VYMTuWtD2KF0TICyilkmRrnhlxdhDMLoQQkmsmhp+b7mzNQaBR9q7ihSc0h8uj2Y06Kn1O9m6t/TFrpqnnibzOcaK5xSq2xIXiJDLZs2d1DuSaZmm+8AI5m52f4mVAPG75aVAxGTU1dH8+NYuAY5y5wSPi6ozl/lbPrQGbqAUjldufUb8G2S4E4jiDsicuJFg13mXP95w6CnNq6oJrBqGG+1lDBJMm5P8YWhvfCaGs8k2r5JhYRaBgz7aISiqM09vs0hpFkYqlIAolhs5bgStKVQ==
  template:
    metadata:
      name: axiom-credentials
      namespace: logging
    type: Opaque
