---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: axiom-credentials
  namespace: logging
spec:
  encryptedData:
    AXIOM_DATASET: AgBm+L2BrmropUd5k/wHuUlYZuqVYl+yU6ZpCq7/3b0p+4g82ryK7R8sl+9dtmiKXD6HPIaSwpcJX8EKTdBDiQygzO2dsyGYU1ffPP0Bd0g8w2Ui9vG66hK0BT8AhrwEWQAr/9L8M66uK1Y6BVJelfIXEpOiLRmL8KoPD8EV910IbYQo/EKAjj0gXyiagok38CazQnCnpZg4F9O+PRiGq6vsrsBaQXnQaYfNOGJunKihmeMYHnU9K+TYVF3inb15GoZ1t8NzSKaip0jiIDQyfgf2cyHw0Xt1KRZpwh5HpXFekC8q/iQjN4xBqcHNKG2XcZ1g34DZo1B249vf6kGR9jTIavB0hSBDl5BULT1TJKfGle8rG6aWXwwijEiDc723nAd6RON7/+hUOXXbWm44lUUmNQVtjZ7X9YFm82lMMonWlnL0C67n937IEM/rtQE/dYyDRcOSW6r+qrmk0mYgg875FnMPVC9hqLe3v8AGIk3eW87NOrgxht5vr30gI63a88Z/a4gE+I0Syhh5QOwybzn41rcjHNWQb0MJq9+zEpO4EECqtH5mn6ZlYLGEGk4xmH5eq12r3CSmC5qaeBa5IKGOOrYYuOGv/edSkzrXiXsKsELJoFRAcAXT2Smg2Bw3pBkmGdi5ZjO21vq9CwtXxUfo5mJBeHxv4nHb1FQ8o/Hs+X9CTTCRsao15eul2wNgh9M7TSpH95vhCpyGpd/YYno=
    AXIOM_TOKEN: AgCmT6oV+FrkXi9i0bModYBNENpD8VuExEXfiyazZxAneAIKf4Go2ZrzFokuD8/bSY4BBdRjSF4wXuFQnK41WnOYRz36ybQRgAx8vxYdEYDOk24SuK5j5GJ8on0ekRHYE6EMllhHDMoCwN+z+XbmGWh1kcuI64I0ewgy8vPw2kTnQAi6i3LfZKk0aUCA4buRgX7JjOXffohZLugjcvZPpF/96GjZ6b28g9n2vzvahxSwep1ws47CqzZxRG3P0UoNmOD8x0yYD0yQID/o6xk72bZe4mrXZsTaOFGsdHNUhcnxk2tFn0uZZfuTsKDyiO+jDs0XET1zjg/qQ3aik+X2t1sJ58Y89d7MJC4XJpM/VGfd8iPlIoDC04sPiPmlu8NcYSkSnd6H87Vgr9UNSLxxL+wextECcPdOfztq1WRnARD+GLSoxpTPLeiNUHGAapJUAEPJGnAgLlfmTaM29DE5q7eeTCj8LSwnSJ4YGQOiSwDekKjyDc2QWNTYvXgIhbDE0H8tpXg8wqiXQHlQdaoeLkfSmm6MzKeH5rfnSGSOMcPSO51Z7USsrTDuOmEzMbdPC5aX2EQHfEU1bYJCVi242Nl8S+0qepI4c8IB8m69JYDfP4zSZi2qjEYizYWKE9xwpvweQ9b/ybMCG8ATF33RCKfKKeR43fwiBODi/ZA78R3gIByKHYF12EixXgysivIuR+VoE9qqktPYfOC1QyY+jds4IoQ1Jy/CdChbiWVni2tVgw4J3kQLHJ9bhw==
  template:
    metadata:
      name: axiom-credentials
      namespace: logging
    type: Opaque
