apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: logging
data:
  vector.yaml: |
    data_dir: /var/lib/vector

    sources:
      kubernetes_logs:
        type: kubernetes_logs
        self_node_name: ${VECTOR_SELF_NODE_NAME}

    sinks:
      axiom:
        type: http
        inputs:
          - kubernetes_logs
        uri: https://api.axiom.co/v1/datasets/${AXIOM_DATASET}/ingest
        method: post
        auth:
          strategy: bearer
          token: ${AXIOM_TOKEN}
        compression: gzip
        encoding:
          codec: json
        framing:
          method: newline_delimited
