apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blog
  namespace: argocd
spec:
  description: My personal ghost blog
  sourceRepos:
    - https://github.com/cjwillis48/blog.git
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: blog
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: bitnami.com
      kind: SealedSecret
    - group: batch
      kind: CronJob
    - group: batch
      kind: Job
