apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: home-assistant
  namespace: argocd
spec:
  description: Home Assistant (hostNetwork, Longhorn PVC / SQLite)
  sourceRepos:
    - https://github.com/cjwillis48/home-assistant.git
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: home-assistant
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: networking.k8s.io
      kind: Ingress
    - group: bitnami.com
      kind: SealedSecret
