apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingresses
  namespace: argocd
spec:
  description: LAN ingress definitions for *.lan.charliewillis.com
  sourceRepos:
    - git@github.com:cjwillis48/k8s-infra.git
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: "*"
  namespaceResourceWhitelist:
    - group: networking.k8s.io
      kind: Ingress
