apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  # Pinned Argo CD install manifest.
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml
  - network-policies.yml
  - apps/argocd.yml
  - apps/blog.yml
  - apps/cloudflared.yml
  - apps/sealed-secrets.yml
